apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: akshayraina/dockeransiblejenkins:8d8316c
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name:  jenkins-service
spec:
  selector:
    app:  jenkins
  type:  LoadBalancer
  ports:
  - name:  http
    protocol: TCP
    port:  8080
    targetPort:  8099